### PR TITLE
Enable aarch64

### PR DESCRIPTION
**Pull request by hfiguiere**
Build on aarch64. The app start on Raspberry Pi (64 bits OS), however I don't really know how to test it further.

### CODE REVIEW

**Comment by abma** [comment]
spring doesn't work on aarch64: thats why there are no builds for it: IMHO its confusing for users when springlobby will fail with sth. like "no engine version available" errors.

is there any use of springlobby on such a platform?

**Comment by hfiguiere** [comment]
> spring doesn't work on aarch64: thats why there are no builds for it: IMHO its confusing for users when springlobby will fail with sth. like "no engine version available" errors.

Can you clarfiy? There is no such information in the README.

> 
> is there any use of springlobby on such a platform?

why not?

**Comment by abma** [comment]
> > spring doesn't work on aarch64: thats why there are no builds for it: IMHO its confusing for users when springlobby will fail with sth. like "no engine version available" errors.
> 
> Can you clarfiy? There is no such information in the README.

https://springrts.com/wiki/Spring_on_ARM

> > is there any use of springlobby on such a platform?
> 
> why not?

because users will complain that it doesn't work.

**Comment by hfiguiere** [comment]
> > > spring doesn't work on aarch64: thats why there are no builds for it: IMHO its confusing for users when springlobby will fail with sth. like "no engine version available" errors.
> > 
> > 
> > Can you clarfiy? There is no such information in the README.
> 
> https://springrts.com/wiki/Spring_on_ARM
> 

This doesn't clarify. It just tell something doesn't build, but here everything build. Probably because I don't understand what this do exactly.

Where does that engine come from since apparently it's not build as part of the flatpak?

**Comment by abma** [comment]
springlobby is a program to join battlerooms:

https://springlobby.springrts.com/screenshots/04.png

when a battle is started, the spring engine with a game is stared:

https://springrts.com/wiki/Games


as the spring engine doesn't compile on aarch64 and and so no game can't be started, springlobby is not very useful as you can't play the games... you only could chat, but for that you could also use a matrix client or even webchat:

https://springrts.com/matrix/

thats why i asked: is there an other reason to have springlobby on aarch64 without the spring engine?

**Pull request closed without merging**
